apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: argocd-aggregator
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: aggregator
  name: argocd-aggregator
